[package]
name = "debrix_shared"
version = "0.1.0"
authors = ["Elias Skogevall"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.debrixc]
path = "../../../../crates/debrixc"
