[package]
name = "dist_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.debrix_compiler]
path = "../debrix_compiler"

[dependencies.dist_shared]
path = "../_shared"
