[package]
name = "dist_node"
version = "0.1.0"
authors = ["Elias Skogevall"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]

[dependencies.debrix_compiler]
path = "../debrix_compiler"

[dependencies.dist_shared]
path = "../_shared"
