name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - uses: jetli/wasm-pack-action@v0.3.0
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - run: cargo build --all-features
      - run: cargo test
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          always-auth: true
          registry-url: https://npm.pkg.github.com
          
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: npm run build
      - run: npm run lint
      - run: npm run test
